# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FARest <- function(y, u, u0, p, d, bwp) {
    .Call('_mxfar_FARest', PACKAGE = 'mxfar', y, u, u0, p, d, bwp)
}

MXFARest <- function(SeriesNum, Tlength, y, u, u0, p, d, bwp) {
    .Call('_mxfar_MXFARest', PACKAGE = 'mxfar', SeriesNum, Tlength, y, u, u0, p, d, bwp)
}

